Task BUZZ-17
sorinlzr/swe-backend pull request #5
Opened 2024-01-20 14:55 UTC by LeitgebMathias

Add Following and Unfollowing of Users
Add "GetFollowedUserFavorites"
Small Changes to AuthController

Important : 
To get the new Endpoints working I had to adjust the Endpoint Paths for 
* Get One User
* Update User

This may need adjustments in the Frontend!!
New Paths : 
* userRouter.get('/user/:username', userController.getOneUser);
* userRouter.put('/user/:username', userController.updateUser);

The Changes in AuthController should not affect the working Version.

If you have any Questions hit me up!

![giphy-20](https://github.com/sorinlzr/swe-backend/assets/113138257/5340dc30-747a-4630-bb7f-9e1727543905)

2024-01-20 20:14 UTC, sorinlzr commented on src/controllers/UserController.ts
> +const getFollowedUsersFavorites = asyncHandler(async (req, res, next) => {
Shouldn't this function be called  `getFollowedUsersWithFavorites` ?

2024-01-20 20:55 UTC, sorinlzr commented on src/controllers/UserController.ts
> +
you can replace this part with the snippet below. The difference is that it's not doing queries in a loop, instead it's doing only one query and directly filters the results that have at least one favorite
```
 const followedUsersWithFavorites = await User.find({ _id: { $in: user.followedUsers},
            $where: "this.favorites.length > 0"}).populate({
            path: 'favorites',
            populate: {
                path: 'type',
                model: 'Category'
            },
            model: 'Favorite'
        });
        ```

2024-01-20 20:58 UTC, sorinlzr commented on src/controllers/UserController.ts
> +userController.getFollowedUsersFavorites = getFollowedUsersFavorites;
please also rename these two to `getFollowedUsersWithFavorites `

2024-01-20 20:59 UTC, sorinlzr requested changes
Looks good and I tested it with something that I am currently implementing. There;s only a small change in the query from the db

2024-01-20 23:16 UTC, sorinlzr commented on src/routers/userRouter.ts
> +userRouter.put('/user/:username', userController.updateUser);
Why did you add this extra endpoint path? please revert it and move the paths with dynamic param at the end. 
Express matches the routes in the order they are written, so the `/follow` paths should come first. 
You can add a check in the `createUser` function so that a user with the username `follow` can't be created.

2024-01-21 09:28 UTC, LeitgebMathias commented on src/controllers/UserController.ts
> +const getFollowedUsersFavorites = asyncHandler(async (req, res, next) => {
Yes - thanks, good catch!

2024-01-21 09:30 UTC, LeitgebMathias commented on src/controllers/UserController.ts
> +
Good to know - thanks!

2024-01-21 09:30 UTC, LeitgebMathias commented on src/controllers/UserController.ts
> +userController.getFollowedUsersFavorites = getFollowedUsersFavorites;
Done!

2024-01-21 09:31 UTC, LeitgebMathias commented on src/routers/userRouter.ts
> +userRouter.put('/user/:username', userController.updateUser);
Did not know, that they get processed by "input-order"
Thanks!

2024-01-21 14:51 UTC, sorinlzr approved these changes

2024-01-21 14:52 UTC, merged